baseURL = "/"
languageCode = "en-us"
title = "My Aliens blog"
theme = "parsa-hugo"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/headroom/headroom.js"
  [[params.plugins.js]]
  URL = "plugins/instafeed/instafeed.min.js"
  [[params.plugins.js]]
  URL = "plugins/masonry/masonry.js"
  [[params.plugins.js]]
  URL = "plugins/reading-time/readingTime.min.js"
  [[params.plugins.js]]
  URL = "plugins/smooth-scroll/smooth-scroll.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"


[[menu.main]]
name = "feed"
url = "posts"
[[menu.main]]
name = "about"
url = "about"
[[menu.main]]
name = "contact"
url = "contact"


[params]
logo = "logo.gif"
[params.search]
enable = true
author = "Aliens"


[params.footer]
	[[params.footer.Addresses]]
		address = " Yangon"

	[[params.footer.contacts]]
		contactInfo = "Tel : 09 796 801 766"
	[[params.footer.contacts]]
		contactInfo = "Mail : zayarmoekaung0@gmail.com"




